export const testData = {
  status: "OK",
  request_id: "f497c2c2-a7e6-42ec-8a6a-e3c307f4e98c",
  parameters: {
    query: "iPhone",
    country: "US",
    sort_by: "RELEVANCE",
    page: 1,
    is_prime: false,
  },
  data: {
    total_products: 486,
    country: "US",
    domain: "www.amazon.com",
    products: [
      {
        asin: "B08PP5MSVB",
        product_title:
          "Apple iPhone 12, 64GB, Black - Fully Unlocked (Renewed)",
        product_price: "$265.00",
        product_original_price: "$278.99",
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 26479,
        product_url: "https://www.amazon.com/dp/B08PP5MSVB",
        product_photo:
          "https://m.media-amazon.com/images/I/51fYXSnSu9L._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 59,
        product_minimum_offer_price: "$243.99",
        is_best_seller: true,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "4K+ bought in past month",
        delivery: "FREE delivery Oct 30 - 31",
        has_variations: true,
      },
      {
        asin: "B07ZPKN6YR",
        product_title: "Apple iPhone 11, 64GB, Black - Unlocked (Renewed)",
        product_price: "$205.00",
        product_original_price: "$223.00",
        currency: "USD",
        product_star_rating: "4.2",
        product_num_ratings: 53376,
        product_url: "https://www.amazon.com/dp/B07ZPKN6YR",
        product_photo:
          "https://m.media-amazon.com/images/I/61MG3m5FhIL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 52,
        product_minimum_offer_price: "$183.99",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        product_availability: "Only 1 left in stock - order soon.",
        climate_pledge_friendly: true,
        sales_volume: "4K+ bought in past month",
        delivery:
          "FREE delivery Oct 29 - 30 Or fastest delivery Tue, Oct 29 Only 1 left in stock - order soon.",
        has_variations: true,
      },
      {
        asin: "B0CMPMY9ZZ",
        product_title: "Apple iPhone 15, 128GB, Black - Unlocked (Renewed)",
        product_price: "$583.22",
        product_original_price: "$615.00",
        currency: "USD",
        product_star_rating: "4.4",
        product_num_ratings: 648,
        product_url: "https://www.amazon.com/dp/B0CMPMY9ZZ",
        product_photo:
          "https://m.media-amazon.com/images/I/51PtFHUPjBL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 38,
        product_minimum_offer_price: "$564.00",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "1K+ bought in past month",
        delivery: "FREE delivery Oct 30 - 31",
        has_variations: false,
      },
      {
        asin: "B0BN72FYFG",
        product_title: "Apple iPhone 14, 128GB, Midnight - Unlocked (Renewed)",
        product_price: "$418.90",
        product_original_price: "$457.00",
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 2982,
        product_url: "https://www.amazon.com/dp/B0BN72FYFG",
        product_photo:
          "https://m.media-amazon.com/images/I/61WUSYIQdKL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 54,
        product_minimum_offer_price: "$395.08",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        product_availability: "Only 14 left in stock - order soon.",
        climate_pledge_friendly: false,
        sales_volume: "2K+ bought in past month",
        delivery:
          "FREE delivery Oct 30 - 31 Only 14 left in stock - order soon.",
        has_variations: true,
      },
      {
        asin: "B07P6Y7954",
        product_title: "Apple iPhone XR, 64GB, Black - Unlocked (Renewed)",
        product_price: "$170.00",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.4",
        product_num_ratings: 65214,
        product_url: "https://www.amazon.com/dp/B07P6Y7954",
        product_photo:
          "https://m.media-amazon.com/images/I/51z1UO6N6LL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 46,
        product_minimum_offer_price: "$152.00",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        product_availability: "Only 3 left in stock - order soon.",
        climate_pledge_friendly: true,
        sales_volume: "2K+ bought in past month",
        delivery:
          "FREE delivery Oct 30 - 31 Only 3 left in stock - order soon.",
        has_variations: true,
      },
      {
        asin: "B088NQSLGN",
        product_title:
          "Apple iPhone SE (2nd Generation), US Version, 64GB, White - Unlocked (Renewed)",
        product_price: "$119.00",
        product_original_price: "$156.86",
        currency: "USD",
        product_star_rating: "4.2",
        product_num_ratings: 19149,
        product_url: "https://www.amazon.com/dp/B088NQSLGN",
        product_photo:
          "https://m.media-amazon.com/images/I/61hpoPMVgqL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 23,
        product_minimum_offer_price: "$98.99",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: true,
        sales_volume: "1K+ bought in past month",
        delivery: "FREE delivery Wed, Oct 30",
        has_variations: true,
      },
      {
        asin: "B09LNW3CY2",
        product_title: "Apple iPhone 13, 128GB, Midnight - Unlocked (Renewed)",
        product_price: "$394.00",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 12674,
        product_url: "https://www.amazon.com/dp/B09LNW3CY2",
        product_photo:
          "https://m.media-amazon.com/images/I/61VuVU94RnL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 48,
        product_minimum_offer_price: "$345.86",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        product_availability: "Only 1 left in stock - order soon.",
        climate_pledge_friendly: true,
        sales_volume: "2K+ bought in past month",
        delivery:
          "FREE delivery Oct 30 - 31 Only 1 left in stock - order soon.",
        has_variations: true,
      },
      {
        asin: "B0BDY74L2P",
        product_title:
          "Apple iPhone SE 3rd Gen, 64GB, Starlight - Unlocked (Renewed)",
        product_price: "$172.90",
        product_original_price: "$195.20",
        currency: "USD",
        product_star_rating: "4.2",
        product_num_ratings: 1987,
        product_url: "https://www.amazon.com/dp/B0BDY74L2P",
        product_photo:
          "https://m.media-amazon.com/images/I/511tZTsZESL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 30,
        product_minimum_offer_price: "$159.83",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        product_availability: "Only 13 left in stock - order soon.",
        climate_pledge_friendly: false,
        sales_volume: "400+ bought in past month",
        delivery:
          "FREE delivery Oct 29 - 31 Only 13 left in stock - order soon.",
        has_variations: true,
      },
      {
        asin: "B0BYLN65JD",
        product_title:
          "Apple iPhone 14, 128GB, Blue - Unlocked (Renewed Premium)",
        product_price: "$530.00",
        product_original_price: "$559.00",
        currency: "USD",
        product_star_rating: "4.2",
        product_num_ratings: 833,
        product_url: "https://www.amazon.com/dp/B0BYLN65JD",
        product_photo:
          "https://m.media-amazon.com/images/I/61bK6PMOC3L._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 16,
        product_minimum_offer_price: "$481.27",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        product_availability: "Only 5 left in stock - order soon.",
        climate_pledge_friendly: false,
        sales_volume: "100+ bought in past month",
        delivery:
          "FREE delivery Tomorrow, Oct 26 Only 5 left in stock - order soon.",
        has_variations: true,
      },
      {
        asin: "B08PNN2SKF",
        product_title: "Apple iPhone 12 Mini, 64GB, Blue - Unlocked (Renewed)",
        product_price: "$216.65",
        product_original_price: "$311.76",
        currency: "USD",
        product_star_rating: "4",
        product_num_ratings: 13702,
        product_url: "https://www.amazon.com/dp/B08PNN2SKF",
        product_photo:
          "https://m.media-amazon.com/images/I/51-ZD+JBZ7L._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 32,
        product_minimum_offer_price: "$190.60",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        product_availability: "Only 4 left in stock - order soon.",
        climate_pledge_friendly: true,
        sales_volume: "1K+ bought in past month",
        delivery:
          "FREE delivery Oct 30 - 31 Only 4 left in stock - order soon.",
        has_variations: true,
      },
      {
        asin: "B0CRHZZLYR",
        product_title:
          "Apple iPhone 15 Pro Max, 256GB, Blue Titanium - Unlocked (Renewed Premium)",
        product_price: "$999.97",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "3.7",
        product_num_ratings: 45,
        product_url: "https://www.amazon.com/dp/B0CRHZZLYR",
        product_photo:
          "https://m.media-amazon.com/images/I/31P+RImwnlL._AC_UY500_FMwebp_QL65_.jpg",
        product_num_offers: 14,
        product_minimum_offer_price: "$919.97",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        product_availability: "Only 11 left in stock - order soon.",
        climate_pledge_friendly: false,
        sales_volume: "400+ bought in past month",
        delivery:
          "FREE delivery Wed, Oct 30 Only 11 left in stock - order soon.",
        has_variations: false,
      },
      {
        asin: "B08PN7ZG7F",
        product_title:
          "Apple iPhone 12 Pro 5G, US Version, 256GB, Graphite - Unlocked (Renewed)",
        product_price: "$396.00",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 10615,
        product_url: "https://www.amazon.com/dp/B08PN7ZG7F",
        product_photo:
          "https://m.media-amazon.com/images/I/51bf95umgzL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 24,
        product_minimum_offer_price: "$341.64",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: true,
        sales_volume: "500+ bought in past month",
        delivery: "FREE delivery Wed, Oct 30",
        has_variations: true,
      },
      {
        asin: "B0BGQS8YV4",
        product_title:
          "Apple iPhone 13, 128GB, Pink - Unlocked (Renewed Premium)",
        product_price: null,
        product_original_price: null,
        currency: null,
        product_star_rating: "4.4",
        product_num_ratings: 1446,
        product_url: "https://www.amazon.com/dp/B0BGQS8YV4",
        product_photo:
          "https://m.media-amazon.com/images/I/516QZcrv+dL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 1,
        product_minimum_offer_price: null,
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        product_availability: "Only 7 left in stock (more on the way).",
        climate_pledge_friendly: false,
        sales_volume: "100+ bought in past month",
        delivery:
          "FREE delivery Wed, Oct 30 Or fastest delivery Tomorrow, Oct 26 Only 7 left in stock (more on the way).",
        has_variations: true,
      },
      {
        asin: "B0BN9P1GXC",
        product_title:
          "Apple iPhone 14 Pro Max, 128GB, Deep Purple - Unlocked (Renewed)",
        product_price: "$622.50",
        product_original_price: "$710.64",
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 2391,
        product_url: "https://www.amazon.com/dp/B0BN9P1GXC",
        product_photo:
          "https://m.media-amazon.com/images/I/51KLILQ67nL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 57,
        product_minimum_offer_price: "$606.92",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        climate_pledge_friendly: false,
        sales_volume: "400+ bought in past month",
        delivery: "FREE delivery Oct 30 - 31",
        has_variations: true,
      },
      {
        asin: "B0BN93GPQ7",
        product_title:
          "Apple iPhone 14 Pro, 1TB, Deep Purple - Unlocked (Renewed)",
        product_price: "$780.00",
        product_original_price: null,
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 2247,
        product_url: "https://www.amazon.com/dp/B0BN93GPQ7",
        product_photo:
          "https://m.media-amazon.com/images/I/51aWrQ-VuSL._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 12,
        product_minimum_offer_price: "$722.00",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: true,
        product_availability: "Only 10 left in stock - order soon.",
        climate_pledge_friendly: false,
        sales_volume: "More Buying Choices",
        delivery:
          "FREE delivery Wed, Oct 30 Or fastest delivery Tomorrow, Oct 26 Only 10 left in stock - order soon.",
        has_variations: true,
      },
      {
        asin: "B0CMZD7VCV",
        product_title:
          "Apple iPhone 15 Pro Max, 256GB, Natural Titanium - Unlocked (Renewed)",
        product_price: "$936.96",
        product_original_price: "$989.95",
        currency: "USD",
        product_star_rating: "4.1",
        product_num_ratings: 448,
        product_url: "https://www.amazon.com/dp/B0CMZD7VCV",
        product_photo:
          "https://m.media-amazon.com/images/I/616mZZm8-7L._AC_UY654_FMwebp_QL65_.jpg",
        product_num_offers: 22,
        product_minimum_offer_price: "$899.00",
        is_best_seller: false,
        is_amazon_choice: false,
        is_prime: false,
        product_availability: "Only 2 left in stock - order soon.",
        climate_pledge_friendly: false,
        sales_volume: "100+ bought in past month",
        delivery:
          "FREE delivery Tue, Oct 29 Or fastest delivery Tomorrow, Oct 26 Only 2 left in stock - order soon.",
        has_variations: true,
      },
    ],
  },
};
